### ISSUE TITLE
Fatal server error after retrieving dropps posted by a user

### ISSUE THREAD

**Issue by StevenMccracken** [StevenMccracken/Dropp#14]
Discovered severe error in Pull Request #13. All requests work as intended and catch errors correctly. The error is "primed" when the server receives a GET request at /users/:username/dropps. The error does not occur until the server receives a POST request at /dropps to create a dropp. This request after the GET request causes some confusing logic with the callbacks and tries to send the response to the client twice.

Here is the error call stack:
```
2017-04-27T08:45:35.695Z: POST request received from IP ::1
FIREBASE WARNING: Exception was thrown by user callback. Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at ServerResponse.header (/Users/stevenmccracken/GitHub/School/Dropp/Dropp/node_modules/express/lib/response.js:725:10)
    at ServerResponse.send (/Users/stevenmccracken/GitHub/School/Dropp/Dropp/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/Users/stevenmccracken/GitHub/School/Dropp/Dropp/node_modules/express/lib/response.js:256:15)
    at firebase.getDroppsByUser.dbResult (/Users/stevenmccracken/GitHub/School/Dropp/Dropp/modules/router_mod.js:238:20)
    at droppsRef.on.droppsSnapshot (/Users/stevenmccracken/GitHub/School/Dropp/Dropp/modules/firebase_mod.js:280:12)
    at /Users/stevenmccracken/GitHub/School/Dropp/Dropp/node_modules/firebase-admin/lib/database/database.js:126:791
    at Ac (/Users/stevenmccracken/GitHub/School/Dropp/Dropp/node_modules/firebase-admin/lib/database/database.js:63:165)
    at jf (/Users/stevenmccracken/GitHub/School/Dropp/Dropp/node_modules/firebase-admin/lib/database/database.js:126:215)
    at kf (/Users/stevenmccracken/GitHub/School/Dropp/Dropp/node_modules/firebase-admin/lib/database/database.js:125:539) 
/Users/stevenmccracken/GitHub/School/Dropp/Dropp/node_modules/firebase-admin/lib/database/database.js:63
(d="0"+d),c+=d;return c.toLowerCase()}var zc=/^-?\d{1,10}$/;function tc(a){return zc.test(a)&&(a=Number(a),-2147483648<=a&&2147483647>=a)?a:null}function Ac(a){try{a()}catch(b){setTimeout(function(){N("Exception was thrown by user callback.",b.stack||"");throw b;},Math.floor(0))}}function Bc(a,b,c){Object.defineProperty(a,b,{get:c})}function Cc(a,b){var c=setTimeout(a,b);"object"===typeof c&&c.unref&&c.unref();return c};function Dc(a){var b={},c={},d={},e="";try{var f=a.split("."),b=bb(hc(f[0])||""),c=bb(hc(f[1])||""),e=f[2],d=c.d||{};delete c.d}catch(g){}return{yg:b,He:c,data:d,og:e}}function Ec(a){a=Dc(a);var b=a.He;return!!a.og&&!!b&&"object"===typeof b&&b.hasOwnProperty("iat")}function Fc(a){a=Dc(a).He;return"object"===typeof a&&!0===y(a,"admin")};function Gc(a,b,c){this.type=Hc;this.source=a;this.path=b;this.children=c}Gc.prototype.Jc=function(a){if(this.path.e())return a=this.children.subtree(new J

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at ServerResponse.header (/Users/stevenmccracken/GitHub/School/Dropp/Dropp/node_modules/express/lib/response.js:725:10)
    at ServerResponse.send (/Users/stevenmccracken/GitHub/School/Dropp/Dropp/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/Users/stevenmccracken/GitHub/School/Dropp/Dropp/node_modules/express/lib/response.js:256:15)
    at firebase.getDroppsByUser.dbResult (/Users/stevenmccracken/GitHub/School/Dropp/Dropp/modules/router_mod.js:238:20)
    at droppsRef.on.droppsSnapshot (/Users/stevenmccracken/GitHub/School/Dropp/Dropp/modules/firebase_mod.js:280:12)
    at /Users/stevenmccracken/GitHub/School/Dropp/Dropp/node_modules/firebase-admin/lib/database/database.js:126:791
    at Ac (/Users/stevenmccracken/GitHub/School/Dropp/Dropp/node_modules/firebase-admin/lib/database/database.js:63:165)
    at jf (/Users/stevenmccracken/GitHub/School/Dropp/Dropp/node_modules/firebase-admin/lib/database/database.js:126:215)
    at kf (/Users/stevenmccracken/GitHub/School/Dropp/Dropp/node_modules/firebase-admin/lib/database/database.js:125:539)

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Dropp@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Dropp@1.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Dropp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Dropp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Dropp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/stevenmccracken/GitHub/School/Dropp/Dropp/npm-debug.log
```

**Comment by RichCherng** [comment]
Firebase.on is not close before we send the response back.

Either change it to .once() or reponse outside of the scope
